[package]
name = "bliss-rs"
version = "0.1.0"
authors = ["Polochon-street <polochonstreet@gmx.fr>"]
edition = "2018"
license = "GNU GPLv3"
description = "A song analysis library for making playlists"
homepage = "https://lelele.io/bliss.html"
repository = "https://github.com/Polochon-street/bliss-rs"
readme = "README.md"

[features]
# Building ffmpeg until either
# https://github.com/zmwangx/rust-ffmpeg/pull/60
# or https://github.com/zmwangx/rust-ffmpeg/pull/62 is in
default = ["aubio-rs/static", "build-ffmpeg"]
build-ffmpeg = ["ffmpeg-next/build"]
bench = []

[dependencies]
ripemd160 = "0.9.0"
ndarray-npy = "0.8.0"
ndarray = { version = "0.15.0", features = ["rayon"] }
num_cpus = "1.13.0"
ndarray-stats = "0.5.0"
rustfft = "5.0.1"
lazy_static = "1.4.0"
rayon = "1.5.0"
crossbeam = "0.8.0"
noisy_float = "0.2.0"
ffmpeg-next = "4.3.8"
log = "0.4.14"
env_logger = "0.8.3"
thiserror = "1.0.24"
# Until https://github.com/aubio/aubio/issues/336 is somehow solved
aubio-rs = {version = "0.2.0", path = "./aubio-rs/aubio-rs"}

[dev-dependencies]
mpd = "0.0.12"
rusqlite = "0.25.0"
dirs = "3.0.1"
tempdir = "0.3.7"
clap = "2.33.3"
anyhow = "1.0.40"
